// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ImportLocal(arg1) {
  return window['go']['main']['App']['ImportLocal'](arg1);
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncAndImportLocal() {
  return window['go']['main']['App']['SyncAndImportLocal']();
}

export function SyncDatabase() {
  return window['go']['main']['App']['SyncDatabase']();
}

export function SyncToTest() {
  return window['go']['main']['App']['SyncToTest']();
}
