// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function ImportLocal(arg1:string):Promise<void>;

export function PickFile():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SyncAndImportLocal():Promise<void>;

export function SyncDatabase():Promise<void>;

export function SyncToTest():Promise<void>;
